UPLOAD_FOLDER = 'server/uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

initial_categories = ["All", "Others"]
institution_names = [
    "Adamjee Cantonement College (ACC)",
    "Aga Khan School / Aga Khan Academy (AKS/AKA)",
    "Academia English Medium School (ACDEMS)",
    "Australian International School (AusIS)",
    "American International School (AISD)",
    "Agrani School and College (AGSC)",
    "Alliance Française de Dhaka (AFD)",
    "Armanitola Government High School (AGHS)",
    "Atomic Energy Research Establishment School and College (A.E.R.E school and college)",
    "Azimpur Government Girls' School and College (AGGSC)",
    "Bangladesh International Tutorial (BIT)",
    "BAF Shaheen English Medium School and College (BAFSEMSC)",
    "BAF Shaheen School And College (BAFSSC)",
    "Bangladesh International School and College (BISC)",
    "Badda Alatunnessa Higher Secondary School (BAHSS)",
    "Bandura Holy Cross School & Collage (BHCSC)",
    "Baridhara Scholars Institution (BSI)",
    "Bashir Uddin Adarsha School and College (BUASC)",
    "Birshrestha Noor Mohammad Public College (BNMPC)",
    "Bright School and College (BSC)",
    "Bulbul Lalitakala Academy (BLA)",
    "Birshrestha Noor Mohammad Public School (BNMPC)",
    "Canadian Trillinium School (CTS)",
    "Cardiff International School Dhaka (CISD)",
    "Dhanmondi Government Boys’ High School (DGBHS)",
    "Dhaka Residential Model College (DRMC)",
    "Dhaka Government Muslim High School (DGMHS)",
    "Delhi Public School (DPS)",
    "Daffodil International School (DIS)",
    "Dhaka Collegiate School (DCS)",
    "Dhamrai Hardinge High School and College (DHHSC)",
    "Dhanmondi Tutorial (DT)",
    "East West International School (EWIS)",
    "European Standard School (ESS)",
    "Government Laboratory High School (GLHS)",
    "Government Science High School (GSHC)",
    "Government Shaheed Suhrawardy College (GSSC)",
    "Graphic Arts Institute (Dhaka) (GAI)",
    "Green Gems International School (GGIS)",
    "Holy Cross College, Dhaka (HCC)",
    "Holy Cross Girls' High School (Dhaka) (HCGHS)",
    "Hurdco International School (HUIS)",
    "Ideal School and College (ISS)",
    "International Hope School Bangladesh (ISHSB)",
    "Jatrabari Ideal High School (JIHS)",
    "K. L. Jubilee High School & College (KLJBHSC)",
    "Kabi Nazrul Government College (KZGC)",
    "Kalshi Islamia High School (KIHSC)",
    "LORDS-An English Medium School (LEMS)",
    "Monipur High School And College (MHSC)",
    "Motijheel Government Boys' High School (MGBHS)",
    "Mastermind School (MS)",
    "Maple Leaf International School (MLIS)",
    "Manarat International School And College (MISC)",
    "Matuail Adarsha High School (MAHS)",
    "Milestone College (MC)",
    "Mirpur Government High School (MGHS)",
    "Mohammadpur Preparatory School & College (MPSC)",
    "Morning Glory School and College (MGSC)",
    "Muslim Government High School, Dhaka (MGSD)",
    "Nabakumar Institution (NI)",
    "National Bangla High School (NBHS)",
    "National Ideal College (NIC)",
    "New Vision School and College (NVSC)",
    "Noubahini College, Dhaka (NCD)",
    "Notre Dame School And College (NDC)",
    "Oxford International School (OIS)",
    "Playpen School (PS)",
    "Park International School and College, Dhaka (PISCD)",
    "Pogose School (PS)",
    "Rajuk Uttara Model College (RUMC)",
    "Shamsul Haque Khan School and College (SHKSC)",
    "St Joseph Higher Secondary School (STJHS)",
    "St. Gregory's High School & College (STGHS)",
    "South Point School and College (SPSC)",
    "Scholastica Mirpur / Uttara (school)",
    "Sunbeams School (SS)",
    "South Breeze School (SBS)",
    "Sunnydale School (SDS)",
    "Sir John Wilson School (SJWS)",
    "S.F.X Greenherald School (GH)",
    "St. Francis Xavier's Girls' High School (SFXGHS)",
    "Saint Joseph School of Industrial Trades (SJ)",
    "Savar Cantonment Public School and College (SCPC)",
    "Scholastica (school)",
    "Shaheed Bir Uttam Lt. Anwar Girls College (SBUAGC)",
    "Shaheed Ramiz Uddin Cantonment College (SRUCC)",
    "Sher-e-Bangla Nagar Government Boys' High School (SBGBHS)",
    "Siddheswari Boys' High School (SBHS)",
    "Sydney International School (SIS)",
    "The New School Dhaka (TNSD)",
    "T & T High School (TTHS)",
    "Tejgaon Government Girls' High School (TGGHS)",
    "Tejgaon Government High School (TGGHS)",
    "Udayan Higher Secondary School (UDHSS)",
    "University Laboratory School and College (ULSC)",
    "Uttara High School and College (UHSC)",
    "Viqarunnisa Noon School & College (VNSC)",
    "West End High School (Dhaka, Bangladesh) (WEHS)",
    "Willes Little Flower School (WLFS)",
    "Ahsanullah University of Science And Technology (AUST)",
    "American International University-Bangladesh (AIUB)",
    "Anwar Khan Modern University (AKMU)",
    "Asa University Bangladesh (AUB)",
    "Asian University of Bangladesh (AUOB)",
    "Atish Dipankar University of Science and Technology (ADUST)",
    "Bangabandhu Sheikh Mujib Medical University (BSMMU)",
    "Bangabandhu Sheikh Mujibur Rahman Agricultural University (BSMRAU)",
    "Bangabandhu Sheikh Mujibur Rahman Maritime University (BSMRMU)",
    "Bangabandhu Sheikh Mujibur Rahman Science and Technology University (BSMRSTU)",
    "Bangladesh Agricultural University (BAU)",
    "Bangladesh Islami University (BIU)",
    "Bangladesh University (BU)",
    "Bangladesh University of Business and Technology (BUBT_",
    "Bangladesh University of Engineering and Technology (BUET)",
    "BGMEA University of Fashion and Technology (BGMEAUFT)",
    "Canadian University of Bangladesh (CUB)",
    "Central University of Science and Technology (CUST)",
    "Central Women's University (CWU)",
    "City University (CU)",
    "Daffodil Internatioal University (DFIU)",
    "Dhaka International University  (DIU)",
    "Dhaka University of Engineering and Technology (DUET)",
    "East West University (EWT)",
    "Eastern University Bangladesh (EUB)",
    "European University of Bangladesh (EUOB)",
    "Fareast International University (FIU)",
    "Gono Bishwabidalay (GB)",
    "Green University of Bangladesh (GUB)",
    "Hamdard University of Bangladesh (HUB)",
    "IBAIS University",
    "Independent University Bangladesh (IUB)",
    "International Standard University (ISU)",
    "International University of Business Agriculture and Technology (IUBAT)",
    "Ishakha International University Bangladesh (IIUB)",
    "Islamic Arabic University (IAU)",
    "Islamic University of Technology (IUT)",
    "Jagannath University (JU)",
    "Jahangirnagar University (JU)",
    "Jatiya Kabi Kazi Nazrul Islam University (JKKZIU)",
    "Manarat International University (MIU)",
    "Mawlana Bhashani Science and Technology University (MBSTU)",
    "N.P.I. University of Bangladesh (NPIUB)",
    "National University Bangladesh (NUB)",
    "North South University (NSU)",
    "Northern University of Bangladesh (NUOB)",
    "Notre Dame University Bangladesh (NDUB)",
    "Presidency University Bangladesh (PUB)",
    "Prime University (PU)",
    "Primeasia University ((PAU)",
    "Queens University (QU)",
    "Royal University of Dhaka (RUD)",
    "Shanto Mariam University of Creative Technology (SMUCT)",
    "Sheikh Fazilatunnesa Mujib University (SFMU)",
    "Sher-e-Bangla Agricultural University (SBAU)",
    "Sonargaon University (SU)",
    "Southeast University Bangladesh (SEUB)",
    "Stamford University Bangladesh (STUB)",
    "State University of Bangladesh (SUB)",
    "The International University of Scholars (TIUS)",
    "The Millenium University (TMU)",
    "The People's University of Bangladesh (TPUB)",
    "Times University of Bangladesh (TUB)",
    "United International University (UIU)",
    "University of Asia Pacific (UAP)",
    "University of Development Alternative (UDA)",
    "University of Dhaka (UD)",
    "University of Information Technology and Sciences (UITS)",
    "University of Liberal Arts Bangladesh (ULAB)",
    "Unversity of South Asia Bangladesh (USAB)",
    "Uttara University (UU)",
    "Victoria University of Bangladesh (VUB)",
    "World University of Bangladesh (WUB)",
    "Z.H. Sikder University of Science and Technology (ZHSUST)",
    "ZNRF University of Management Sciences (ZNRFUMS)",
    "Other"
]
